// Blue Sky State Rules — Reg D 506(b) & 506(c)
// Source: NASAA EFD Fee Matrix (Jan 2026), Blue Sky Comply, SEC Compliance Solutions
// All 50 states + DC. Fees as of early 2026 — verify before filing.
// Rule 506 offerings are "covered securities" under NSMIA: states may require notice filings
// but may NOT require full registration.

const STATE_RULES = [
  {
    state_code: 'AL',
    state_name: 'Alabama',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Alabama',
    fee_structure: 'Flat',
    fee_amount: 300,
    fee_basis: 'flat',
    fee_notes: '$300 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Late fees may apply — verify with Alabama Securities Commission',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Alabama Securities Commission via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'AK',
    state_name: 'Alaska',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Alaska',
    fee_structure: 'Flat',
    fee_amount: 600,
    fee_basis: 'flat',
    fee_notes: '$600 flat fee. $600 termination fee when offering closes.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with Alaska Division of Banking & Securities',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Alaska Division of Banking & Securities. Note: $600 termination fee required when offering is completed.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'AZ',
    state_name: 'Arizona',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'Mail (paper filing only)',
    efd_eligible: 0,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Arizona',
    fee_structure: 'Flat',
    fee_amount: 250,
    fee_basis: 'flat',
    fee_notes: '$250 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with AZ Corporation Commission',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'PAPER FILING ONLY — Arizona does not accept NASAA EFD. Mail Form D and check payable to Arizona Corporation Commission, Securities Division.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'AR',
    state_name: 'Arkansas',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Arkansas',
    fee_structure: 'Variable',
    fee_amount: 100,
    fee_basis: '0.1% of offering, min $100 max $500',
    fee_notes: '0.1% of total offering amount; minimum $100, maximum $500',
    late_fee_amount: 500,
    late_fee_notes: '$500 late fee if filed 16–365 days late; $1,000 if more than 365 days late',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 100,
    renewal_fee_notes: 'Annual renewal required. 0.1% of increase in offering amount; minimum $100, maximum $500.',
    special_requirements: 'Annual renewal filing required for ongoing offerings. Renewal is based on any increase in offering amount.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'CA',
    state_name: 'California',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D Notice (DFPI)',
    filing_method: 'CA DFPI portal (CalFile)',
    efd_eligible: 0,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in California',
    fee_structure: 'Flat',
    fee_amount: 300,
    fee_basis: 'flat',
    fee_notes: '$300 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with CA DFPI',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'Must file via CA DFPI CalFile portal — NOT via NASAA EFD. Include copy of federal Form D. California is a high-priority jurisdiction with strict enforcement.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'CO',
    state_name: 'Colorado',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Colorado',
    fee_structure: 'Flat',
    fee_amount: 50,
    fee_basis: 'flat',
    fee_notes: '$50 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with CO Division of Securities',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 50,
    renewal_fee_notes: 'Annual renewal required for ongoing offerings. Renewal fee — verify current amount with CO Division of Securities.',
    special_requirements: 'ANNUAL RENEWAL REQUIRED. Colorado requires annual renewal filings for ongoing Reg D offerings. File renewal before the anniversary of the initial filing.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'CT',
    state_name: 'Connecticut',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Connecticut',
    fee_structure: 'Flat',
    fee_amount: 150,
    fee_basis: 'flat',
    fee_notes: '$150 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with CT Department of Banking',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Connecticut Department of Banking via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'DE',
    state_name: 'Delaware',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Delaware',
    fee_structure: 'Variable',
    fee_amount: 200,
    fee_basis: '0.5% of offering, min $200 max $1,000',
    fee_notes: '0.5% of total offering amount; minimum $200, maximum $1,000',
    late_fee_amount: 200,
    late_fee_notes: 'Late fee: 0.5% of offering, max $1,000 if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'Variable fee based on offering size. Late filing triggers additional fee of 0.5% max $1,000.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'DC',
    state_name: 'District of Columbia',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in DC',
    fee_structure: 'Flat',
    fee_amount: 250,
    fee_basis: 'flat',
    fee_notes: '$250 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'DC imposes penalties up to $10,000 per violation for non-compliance',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with DC Department of Insurance, Securities and Banking (DISB) via NASAA EFD. DC penalties for non-compliance can reach $10,000 per violation.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'FL',
    state_name: 'Florida',
    exemption_type: 'both',
    filing_required: 0,
    form_name: null,
    filing_method: null,
    efd_eligible: 0,
    deadline_days: null,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'No state notice filing required in Florida for Reg D 506 offerings',
    fee_structure: 'None',
    fee_amount: 0,
    fee_basis: 'none',
    fee_notes: 'No fee — no filing required',
    late_fee_amount: null,
    late_fee_notes: null,
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'Florida does not require a separate state notice filing for Rule 506(b) or 506(c) covered securities. Federal EDGAR filing is sufficient.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'GA',
    state_name: 'Georgia',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Georgia',
    fee_structure: 'Flat',
    fee_amount: 250,
    fee_basis: 'flat',
    fee_notes: '$250 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with GA Secretary of State',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Georgia Secretary of State, Securities Division via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'HI',
    state_name: 'Hawaii',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Hawaii',
    fee_structure: 'Flat',
    fee_amount: 100,
    fee_basis: 'flat',
    fee_notes: '$100 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with HI Department of Commerce & Consumer Affairs',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Hawaii Department of Commerce & Consumer Affairs, Securities Compliance Branch via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'ID',
    state_name: 'Idaho',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Idaho',
    fee_structure: 'Flat',
    fee_amount: 50,
    fee_basis: 'flat',
    fee_notes: '$50 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with ID Department of Finance',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Idaho Department of Finance via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'IL',
    state_name: 'Illinois',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Illinois',
    fee_structure: 'Flat',
    fee_amount: 100,
    fee_basis: 'flat',
    fee_notes: '$100 flat fee. $100 termination fee.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with IL Secretary of State, Securities Department',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with IL Secretary of State, Securities Department via NASAA EFD. $100 termination fee required when offering is complete.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'IN',
    state_name: 'Indiana',
    exemption_type: 'both',
    filing_required: 0,
    form_name: null,
    filing_method: null,
    efd_eligible: 0,
    deadline_days: null,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'No state notice filing required in Indiana for Reg D 506 offerings',
    fee_structure: 'None',
    fee_amount: 0,
    fee_basis: 'none',
    fee_notes: 'No fee — no filing required',
    late_fee_amount: null,
    late_fee_notes: null,
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'Indiana does not require a separate state notice filing for Rule 506 covered securities. Federal EDGAR filing is sufficient.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'IA',
    state_name: 'Iowa',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Iowa',
    fee_structure: 'Flat',
    fee_amount: 100,
    fee_basis: 'flat',
    fee_notes: '$100 flat fee',
    late_fee_amount: 250,
    late_fee_notes: '$250 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Iowa Insurance Division, Securities Bureau via NASAA EFD. $250 penalty for late filing.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'KS',
    state_name: 'Kansas',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Kansas',
    fee_structure: 'Flat',
    fee_amount: 125,
    fee_basis: 'flat',
    fee_notes: '$125 flat fee',
    late_fee_amount: 250,
    late_fee_notes: '$250 late fee (16–90 days); $500–$2,500 for longer delays',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Kansas Securities Commissioner via NASAA EFD. Significant late filing penalties apply.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'KY',
    state_name: 'Kentucky',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Kentucky',
    fee_structure: 'Flat',
    fee_amount: 250,
    fee_basis: 'flat',
    fee_notes: '$250 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with KY Department of Financial Institutions',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Kentucky Department of Financial Institutions via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'LA',
    state_name: 'Louisiana',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Louisiana',
    fee_structure: 'Flat',
    fee_amount: 300,
    fee_basis: 'flat',
    fee_notes: '$300 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with LA Office of Financial Institutions',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Louisiana Office of Financial Institutions via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'ME',
    state_name: 'Maine',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'Mail (paper filing only)',
    efd_eligible: 0,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Maine',
    fee_structure: 'Flat',
    fee_amount: 300,
    fee_basis: 'flat',
    fee_notes: '$300 flat fee',
    late_fee_amount: 500,
    late_fee_notes: '$500 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'PAPER FILING ONLY — Maine does not accept NASAA EFD. Mail Form D to Maine Office of Securities. $500 late fee penalty.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'MD',
    state_name: 'Maryland',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Maryland',
    fee_structure: 'Flat',
    fee_amount: 100,
    fee_basis: 'flat',
    fee_notes: '$100 flat fee',
    late_fee_amount: 150,
    late_fee_notes: '$150 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Maryland Division of Securities via NASAA EFD. $150 late fee applies.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'MA',
    state_name: 'Massachusetts',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD or MA Secretary of State',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Massachusetts',
    fee_structure: 'Variable',
    fee_amount: 250,
    fee_basis: 'variable: $250–$750 based on offering size',
    fee_notes: 'Variable fee: approximately $250–$750 depending on offering size. Verify current schedule with MA Secretary of State.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with MA Securities Division',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'Massachusetts historically required separate state form filings. Verify current requirements — MA may now accept NASAA EFD. Some sources indicate MA has unique filing procedures for ongoing funds.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'MI',
    state_name: 'Michigan',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Michigan',
    fee_structure: 'Flat',
    fee_amount: 100,
    fee_basis: 'flat',
    fee_notes: '$100 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with MI Department of Insurance and Financial Services',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'Annual renewals are NOT required in Michigan. Michigan does not require a termination date in the original filing.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'MN',
    state_name: 'Minnesota',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Minnesota',
    fee_structure: 'Variable',
    fee_amount: 100,
    fee_basis: '$100 + 1/10 of 1% of offering, max $300',
    fee_notes: '$100 base + 1/10 of 1% (0.1%) of total offering amount; maximum $300 total',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with MN Department of Commerce',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 0,
    renewal_fee_notes: 'Renewal fee applies only if offering amount increases: 1/10 of 1% on the increase, max $199.',
    special_requirements: 'Annual renewal required if offering continues. Renewal fee only charged on increase in offering amount.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'MS',
    state_name: 'Mississippi',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Mississippi',
    fee_structure: 'Flat',
    fee_amount: 300,
    fee_basis: 'flat',
    fee_notes: '$300 flat fee. $300 termination fee. $50 withdrawal fee.',
    late_fee_amount: null,
    late_fee_notes: 'Late fee: 1% of state-sold amount, max $5,000 if filed after 15 days',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 50,
    renewal_fee_notes: '$50 annual renewal fee for ongoing offerings',
    special_requirements: 'Annual renewal required for ongoing offerings ($50 fee). Significant late fee: 1% of MS offering amount, max $5,000. Termination filing required when offering closes ($300).',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'MO',
    state_name: 'Missouri',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Missouri',
    fee_structure: 'Flat',
    fee_amount: 100,
    fee_basis: 'flat',
    fee_notes: '$100 flat fee',
    late_fee_amount: 50,
    late_fee_notes: '$50 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Missouri Securities Division via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'MT',
    state_name: 'Montana',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Montana',
    fee_structure: 'Variable',
    fee_amount: 200,
    fee_basis: '0.1% of offering, min $200 max $1,000',
    fee_notes: '0.1% of total offering amount; minimum $200, maximum $1,000',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with MT Commissioner of Securities',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 200,
    renewal_fee_notes: 'Annual renewal required. Fee: 0.1% of offering, min $200, max $1,000.',
    special_requirements: 'Annual renewal required for ongoing offerings. Renewal fee mirrors initial filing fee structure.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'NE',
    state_name: 'Nebraska',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Nebraska',
    fee_structure: 'Flat',
    fee_amount: 200,
    fee_basis: 'flat',
    fee_notes: '$200 flat fee',
    late_fee_amount: 200,
    late_fee_notes: '$200 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Nebraska Department of Banking & Finance via NASAA EFD. $200 late fee penalty.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'NV',
    state_name: 'Nevada',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Nevada',
    fee_structure: 'Flat',
    fee_amount: 500,
    fee_basis: 'flat',
    fee_notes: '$500 flat fee. $500 termination fee.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with NV Secretary of State, Securities Division',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 500,
    renewal_fee_notes: 'Annual renewal required for ongoing offerings. $500 annual renewal fee.',
    special_requirements: 'ANNUAL RENEWAL REQUIRED at $500/year. Nevada is one of the few states explicitly requiring annual renewal filings for Reg D offerings. Termination filing also required ($500).',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'NH',
    state_name: 'New Hampshire',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in New Hampshire',
    fee_structure: 'Flat',
    fee_amount: 500,
    fee_basis: 'flat',
    fee_notes: '$500 flat fee',
    late_fee_amount: 500,
    late_fee_notes: '$500 late fee (16–90 days); $1,000 (91–365 days)',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with NH Bureau of Securities Regulation via NASAA EFD. Escalating late fees: $500 (16-90 days late) or $1,000 (91-365 days late).',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'NJ',
    state_name: 'New Jersey',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in New Jersey',
    fee_structure: 'Flat',
    fee_amount: 750,
    fee_basis: 'flat',
    fee_notes: '$750 flat fee (one of the highest flat fees)',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with NJ Bureau of Securities',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with New Jersey Bureau of Securities via NASAA EFD. Note: $750 flat fee is among the highest in the country.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'NM',
    state_name: 'New Mexico',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in New Mexico',
    fee_structure: 'Flat',
    fee_amount: 350,
    fee_basis: 'flat',
    fee_notes: '$350 flat fee',
    late_fee_amount: 700,
    late_fee_notes: '$700 (16–25 days late); $1,050 (more than 25 days late)',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with NM Regulation & Licensing Department, Securities Division via NASAA EFD. Escalating late fees.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'NY',
    state_name: 'New York',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: null,
    filing_before_first_sale: 1,
    days_before_first_sale: 1,
    deadline_notes: 'Must file at least 1 business day BEFORE first sale in New York — NOT after.',
    fee_structure: 'Variable',
    fee_amount: 300,
    fee_basis: 'variable: $300 min, up to $2,135 based on offering size',
    fee_notes: 'Variable: minimum $300, maximum $2,135 depending on offering size. Offering increase triggers additional fee.',
    late_fee_amount: 30,
    late_fee_notes: '$30 late fee if filed after required date. $900 fee for offering increases.',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 0,
    renewal_fee_notes: 'Annual amendment required for ongoing offerings — no additional fee. After 4 years of continuous offering, a new Form D filing and new fee is required.',
    special_requirements: 'CRITICAL: NY filing must be made AT LEAST 1 BUSINESS DAY BEFORE first sale — not within 15 days after. Annual amendments required for ongoing offerings (no fee). After 4 years: new Form D + new filing fee required. NY fees are among the highest in the US.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'NC',
    state_name: 'North Carolina',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in North Carolina',
    fee_structure: 'Flat',
    fee_amount: 350,
    fee_basis: 'flat',
    fee_notes: '$350 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with NC Secretary of State, Securities Division',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with North Carolina Secretary of State, Securities Division via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'ND',
    state_name: 'North Dakota',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in North Dakota',
    fee_structure: 'Flat',
    fee_amount: 100,
    fee_basis: 'flat',
    fee_notes: '$100 flat fee. $250 termination fee.',
    late_fee_amount: 250,
    late_fee_notes: '$250 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with ND Securities Department via NASAA EFD. $250 late fee. $250 termination fee required when offering closes.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'OH',
    state_name: 'Ohio',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Ohio',
    fee_structure: 'Flat',
    fee_amount: 100,
    fee_basis: 'flat',
    fee_notes: '$100 flat fee',
    late_fee_amount: 100,
    late_fee_notes: '$100 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Ohio Division of Securities via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'OK',
    state_name: 'Oklahoma',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Oklahoma',
    fee_structure: 'Flat',
    fee_amount: 250,
    fee_basis: 'flat',
    fee_notes: '$250 flat fee',
    late_fee_amount: 250,
    late_fee_notes: '$250 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Oklahoma Department of Securities via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'OR',
    state_name: 'Oregon',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Oregon',
    fee_structure: 'Flat',
    fee_amount: 250,
    fee_basis: 'flat',
    fee_notes: '$250 flat fee. $100 termination fee for offering increases.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with OR Division of Financial Regulation',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Oregon Division of Financial Regulation via NASAA EFD. $100 fee for amendments if offering amount increases.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'PA',
    state_name: 'Pennsylvania',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Pennsylvania',
    fee_structure: 'Variable',
    fee_amount: 525,
    fee_basis: 'variable, approximately $525',
    fee_notes: 'Variable fee, approximately $525. Verify current schedule with PA Securities Commission.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with PA Securities Commission',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Pennsylvania Securities Commission via NASAA EFD. Variable fee structure — confirm before filing.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'RI',
    state_name: 'Rhode Island',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: null,
    filing_before_first_sale: 1,
    days_before_first_sale: 10,
    deadline_notes: 'Must file at least 10 days BEFORE first sale in Rhode Island — NOT after.',
    fee_structure: 'Flat',
    fee_amount: 300,
    fee_basis: 'flat',
    fee_notes: '$300 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with RI Department of Business Regulation',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'CRITICAL: Rhode Island filing must be made AT LEAST 10 DAYS BEFORE first sale — must file before any investor in RI commits.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'SC',
    state_name: 'South Carolina',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in South Carolina',
    fee_structure: 'Flat',
    fee_amount: 300,
    fee_basis: 'flat',
    fee_notes: '$300 flat fee. $300 termination fee.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with SC Secretary of State, Securities Division',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with South Carolina Secretary of State via NASAA EFD. $300 termination fee required when offering closes.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'SD',
    state_name: 'South Dakota',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in South Dakota',
    fee_structure: 'Flat',
    fee_amount: 250,
    fee_basis: 'flat',
    fee_notes: '$250 flat fee',
    late_fee_amount: 275,
    late_fee_notes: '$275 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with South Dakota Division of Insurance via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'TN',
    state_name: 'Tennessee',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Tennessee',
    fee_structure: 'Flat',
    fee_amount: 500,
    fee_basis: 'flat',
    fee_notes: '$500 flat fee. $100 termination fee.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with TN Securities Division',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Tennessee Securities Division via NASAA EFD. $100 termination fee required when offering closes.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'TX',
    state_name: 'Texas',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Texas',
    fee_structure: 'Variable',
    fee_amount: 200,
    fee_basis: '0.1% of offering amount, max $500',
    fee_notes: '0.1% of total offering amount; maximum $500',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with TX State Securities Board',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'Texas does NOT require annual renewal filings. The offering is effective until completed or terminated. File with Texas State Securities Board via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'UT',
    state_name: 'Utah',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Utah',
    fee_structure: 'Variable',
    fee_amount: 0,
    fee_basis: '$0 up to $500K offering; $100 for >$500K',
    fee_notes: '$0 for EDGAR filings up to $500,000 offering amount; $100 for offerings exceeding $500,000',
    late_fee_amount: 500,
    late_fee_notes: '$500 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Utah Division of Securities via NASAA EFD. No fee for offerings under $500K. $500 late fee penalty.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'VT',
    state_name: 'Vermont',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Vermont',
    fee_structure: 'Flat',
    fee_amount: 820,
    fee_basis: 'flat',
    fee_notes: '$820 flat fee (initial and each annual renewal). One of the highest annual fees in the US.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with VT Department of Financial Regulation',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 820,
    renewal_fee_notes: 'ANNUAL RENEWAL REQUIRED at $820/year — same fee as initial filing. Ongoing offerings must file annual renewal on or before anniversary of initial filing.',
    special_requirements: 'ANNUAL RENEWAL REQUIRED ($820/year). Vermont requires annual renewal filings for ongoing Reg D offerings at the same $820 fee as the initial filing. This is one of the highest annual compliance costs in the US. File with Vermont Department of Financial Regulation via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'VA',
    state_name: 'Virginia',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Virginia',
    fee_structure: 'Flat',
    fee_amount: 250,
    fee_basis: 'flat',
    fee_notes: '$250 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with VA State Corporation Commission',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Virginia State Corporation Commission, Division of Securities via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'WA',
    state_name: 'Washington',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Washington',
    fee_structure: 'Flat',
    fee_amount: 300,
    fee_basis: 'flat',
    fee_notes: '$300 flat fee. No fee for annual amendments.',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with WA Department of Financial Institutions',
    renewal_required: 1,
    renewal_period_days: 365,
    renewal_fee: 0,
    renewal_fee_notes: 'Annual amendment required via NASAA EFD on or before the anniversary of the initial filing (or most recent amendment). No fee for amendments.',
    special_requirements: 'ANNUAL RENEWAL REQUIRED (no fee). Washington requires annual amendment via NASAA EFD for ongoing offerings — must file on or before the first anniversary of the most recent filing. No charge for amendments.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'WV',
    state_name: 'West Virginia',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in West Virginia',
    fee_structure: 'Variable',
    fee_amount: 125,
    fee_basis: 'variable, minimum $125',
    fee_notes: 'Variable fee starting at $125. Verify with WV Auditor\'s Office.',
    late_fee_amount: 420,
    late_fee_notes: 'Late fees: $420–$1,800 depending on delay duration',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with West Virginia Auditor\'s Office, Securities Division via NASAA EFD. Significant escalating late fees ($420–$1,800).',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'WI',
    state_name: 'Wisconsin',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Wisconsin',
    fee_structure: 'Flat',
    fee_amount: 200,
    fee_basis: 'flat',
    fee_notes: '$200 flat fee',
    late_fee_amount: 200,
    late_fee_notes: '$200 late fee if filed after 15 days',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Wisconsin Department of Financial Institutions via NASAA EFD.',
    last_verified: '2026-01-01',
  },
  {
    state_code: 'WY',
    state_name: 'Wyoming',
    exemption_type: 'both',
    filing_required: 1,
    form_name: 'Form D (Reg D Notice)',
    filing_method: 'NASAA EFD',
    efd_eligible: 1,
    deadline_days: 15,
    filing_before_first_sale: 0,
    days_before_first_sale: null,
    deadline_notes: 'Within 15 days of first sale in Wyoming',
    fee_structure: 'Flat',
    fee_amount: 200,
    fee_basis: 'flat',
    fee_notes: '$200 flat fee',
    late_fee_amount: null,
    late_fee_notes: 'Verify late fees with WY Secretary of State',
    renewal_required: 0,
    renewal_period_days: null,
    renewal_fee: null,
    renewal_fee_notes: null,
    special_requirements: 'File with Wyoming Secretary of State via NASAA EFD.',
    last_verified: '2026-01-01',
  },
];

module.exports = { STATE_RULES };
